### ISSUE TITLE
margin-right: -.25em;

### ISSUE THREAD

**Issue by ktrhn** [daneden/Toast#31]
line 181 in _grid.scss
Is there a reason for this margin in every grid__col? With this my grid-columns do not take full 100%, it is always visible on the right side that there are some pixels missing.

**Comment by daneden** [comment]
It’s a hack workaround for the whitespace that `inline-block` elements get. .25em is approximately equal to the width of a word space.

Known issue. When I feel confident in a flexbox version of Toast, this will no longer be an issue.
