### ISSUE TITLE
SASS compile error, 'invalid selector for @extend on line 217`

### ISSUE THREAD

**Issue by tconroy** [daneden/Toast#36]
Just grabbed _grid.scss and threw it into my project running SASS v.3.4.16 and getting the following error:

`[gulp-sass] invalid selector for @extend on line 217 in _grid.scss`

the line in question:

```
    &.#{$toast-grid-column-namespace}--m-1-of-4 {
      width: percentage(1/4);
    }
```

although I think it's in reference to this block right below it, as the above doesn't contain an `@extend`...

```
    &.#{$toast-grid-column-namespace}--m-2-of-4 {
      @extend .#{$toast-grid-column-namespace}--m-1-of-2;
    }
```

**Comment by kwisatz** [comment]
Same here. Quick workaround is to simply comment the extends and copy the corresponding css.

In my case I'm using node-sass (v 3.3.3), which in turn uses libsass instead of ruby-sass, so this might have to do with some features not being implemented in libsass yet.
