### ISSUE TITLE
Insane? - Quick Clarification

### ISSUE THREAD

**Issue by ajschmaltz** [daneden/Toast#38]
Is Toast's grid strictly for insane people?  Or, am I (a reasonably sane person) free to use the grid?

**Comment by verticalgrain** [comment]
Could you try to become less sane while using Toast, but then go back to normal at all other times? 

But seriously, using Toast proves your sanity - it is extremely elegant yet still quite powerful and full featured for a grid. It is updated really frequently and uses modern web development practices. Definitely try it out in a codepen if nothing else - it's quick to install.
