### ISSUE TITLE
toast-css isn't available on bower registry

### ISSUE THREAD

**Issue by tnga** [daneden/Toast#46]
Here is my bower's command line log:

``` sh
$ bower install toast-css
bower ENOTFOUND     Package toast-css not found
```

considering the setting package's name in _bower.json_, it seems that this project was not registered. :sake:

**Comment by sebastianhelbig** [comment]
Try `bower install toast-grid`

**Comment by tnga** [comment]
:+1: thank to be prompt :smile:
